version: '3.2'

services:
  agent:
    image: localhost:5000/portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
      # LOG_LEVEL: debug

    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: localhost:5000/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  master: 
    image: localhost:5000/jmeter-master
    deploy:
      mode: replicated
      replicas: 1
     
    networks: 
      - agent_network
    tty: true
  
  slave: 
    image: localhost:5000/jmeter-slave
    networks: 
      - agent_network
    tty: true

  influxdb:
    image: localhost:5000/influxdb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

    networks: 
      - agent_network
    tty: true
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      

  grafana:
    image: localhost:5000/grafana
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

    networks: 
      - agent_network
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      
    depends_on:
      - influxdb

  gitlab:
    image: localhost:5000/gitlab
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - gitlab-storage:/var/opt/gitlab
      - gitlab-storage2:/etc/gitlab
      - gitlab-storage3:/var/log/gitlab


    restart: always
    networks:
     - agent_network
    ports:
     - "80:80"
     - "443:443"

  jenkins:
    image: localhost:5000/jenkins
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
     - agent_network
    volumes:
      - jenkins-storage:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
  grafana-storage:
  influxdb-storage:
  gitlab-storage:
  jenkins-storage:
  gitlab-storage2:
  gitlab-storage3: